#!/usr/bin/env bash
set -e

# Segmenter Native Swift Universal macOS Build Script
# Compiles Universal Binary (arm64 Apple Silicon + x86_64 Intel)
# Bundles static ffmpeg/ffprobe and VLCKit.framework into App Bundle.

# This script now lives inside the Swift package it builds, so SCRIPT_DIR is
# the package root and PROJECT_ROOT has to climb two levels (mac/native -> mac
# -> repo root) rather than one.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SWIFT_DIR="$SCRIPT_DIR"
DIST_DIR="$SCRIPT_DIR/dist"
APP_BUNDLE="$DIST_DIR/Segmenter.app"
BIN_DIR="$APP_BUNDLE/Contents/Resources/bin"
FRAMEWORKS_DIR="$APP_BUNDLE/Contents/Frameworks"

echo "🍏 Building Native Swift Universal macOS App (arm64 + x86_64)..."
echo "--------------------------------------------------------"

# --- Discord Rich Presence client ID ----------------------------------------
# Mirrors core/CMakeLists.txt's .env handling for the Windows/Linux Qt build:
# read a git-ignored .env at the repo root and bake the ID into a generated
# Swift file (itself git-ignored — see .gitignore), so the maintainer's own
# Discord application ID never has to be committed. Always runs, .env or not,
# so a plain `swift build` after this script has run at least once still
# compiles — DiscordConfig.swift just carries an empty clientId until a real
# .env exists.
DISCORD_CLIENT_ID=""
ENV_FILE="$PROJECT_ROOT/.env"
if [ -f "$ENV_FILE" ]; then
    DISCORD_CLIENT_ID="$(grep -E '^DISCORD_CLIENT_ID=' "$ENV_FILE" | tail -1 | cut -d= -f2-)"
fi

GENERATED_DIR="$SWIFT_DIR/Sources/Segmenter/Generated"
mkdir -p "$GENERATED_DIR"
cat > "$GENERATED_DIR/DiscordConfig.swift" <<SWIFT
// Generated by build.sh from .env at build time — do not edit by hand.
// See .env.example at the repo root and DiscordRPCService.swift.
enum DiscordConfig {
    static let clientId = "${DISCORD_CLIENT_ID}"
}
SWIFT

if [ -n "$DISCORD_CLIENT_ID" ]; then
    echo "🎮 Discord Rich Presence enabled (client ID from .env)"
else
    echo "🎮 Discord Rich Presence disabled (no .env / DISCORD_CLIENT_ID — see .env.example)"
fi

cd "$SWIFT_DIR"

echo "🛠️ Compiling arm64 (Apple Silicon)..."
swift build -c release --triple arm64-apple-macosx12.0

echo "🛠️ Compiling x86_64 (Intel)..."
swift build -c release --triple x86_64-apple-macosx12.0

ARM64_BIN="$SWIFT_DIR/.build/arm64-apple-macosx/release/Segmenter"
X86_BIN="$SWIFT_DIR/.build/x86_64-apple-macosx/release/Segmenter"

rm -rf "$DIST_DIR"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"
mkdir -p "$BIN_DIR"
mkdir -p "$FRAMEWORKS_DIR"

echo "🔀 Creating Universal Binary using lipo..."
lipo -create -output "$APP_BUNDLE/Contents/MacOS/Segmenter" "$ARM64_BIN" "$X86_BIN"

cp "$SCRIPT_DIR/Info.plist" "$APP_BUNDLE/Contents/Info.plist"

# Copy VLCKit.framework into App Bundle Frameworks directory
echo "🎬 Bundling VLCKit.framework into App Bundle Frameworks..."
VLC_FRAMEWORK="$SWIFT_DIR/.build/artifacts/vlckit-spm/VLCKit/VLCKit.xcframework/macos-arm64_x86_64/VLCKit.framework"
if [ -d "$VLC_FRAMEWORK" ]; then
    cp -R "$VLC_FRAMEWORK" "$FRAMEWORKS_DIR/"
elif [ -d "$SWIFT_DIR/.build/arm64-apple-macosx/release/VLCKit.framework" ]; then
    cp -R "$SWIFT_DIR/.build/arm64-apple-macosx/release/VLCKit.framework" "$FRAMEWORKS_DIR/"
fi

# Add @executable_path/../Frameworks rpath so dyld loads VLCKit.framework
install_name_tool -add_rpath "@executable_path/../Frameworks" "$APP_BUNDLE/Contents/MacOS/Segmenter" 2>/dev/null || true

# Bundle FFmpeg and FFprobe binaries if available in /tmp or system
echo "📦 Bundling FFmpeg & FFprobe utilities into App Bundle..."
if [ -f "/tmp/ffmpeg" ]; then
    cp "/tmp/ffmpeg" "$BIN_DIR/ffmpeg"
    chmod +x "$BIN_DIR/ffmpeg"
elif command -v ffmpeg &>/dev/null; then
    cp "$(which ffmpeg)" "$BIN_DIR/ffmpeg"
    chmod +x "$BIN_DIR/ffmpeg"
fi

if [ -f "/tmp/ffprobe" ]; then
    cp "/tmp/ffprobe" "$BIN_DIR/ffprobe"
    chmod +x "$BIN_DIR/ffprobe"
elif command -v ffprobe &>/dev/null; then
    cp "$(which ffprobe)" "$BIN_DIR/ffprobe"
    chmod +x "$BIN_DIR/ffprobe"
fi

echo "✅ Universal macOS Application created successfully at:"
echo "   $APP_BUNDLE"

echo "🔍 Verifying Universal Binary Architectures:"
file "$APP_BUNDLE/Contents/MacOS/Segmenter"
lipo -info "$APP_BUNDLE/Contents/MacOS/Segmenter"

if [ -d "$FRAMEWORKS_DIR/VLCKit.framework" ]; then
    echo "🎬 Bundled VLCKit Framework verified at:"
    echo "   $FRAMEWORKS_DIR/VLCKit.framework"
fi

echo "--------------------------------------------------------"
echo "🎉 Build finished! Run directly via:"
echo "   $APP_BUNDLE/Contents/MacOS/Segmenter"
